using System.Collections.ObjectModel; using CommunityToolkit.Mvvm.ComponentModel; using CommunityToolkit.Mvvm.Input; using CodexMultipleAccounts.Core.Profiles; using CodexMultipleAccounts.Core.Launching; using CodexMultipleAccounts.Core.Activation; using CodexMultipleAccounts.App.Terminal;
namespace CodexMultipleAccounts.App.ViewModels;
public partial class MainWindowViewModel:ObservableObject { private readonly ProfileService _profiles; private readonly CodexLaunchService _launch=new(); private readonly GlobalActivationService _activation; private readonly ProcessTerminalLauncher _embedded=new(); private readonly ExternalTerminalLauncher _external=new(); public ObservableCollection<CodexProfile> Profiles{get;}=[]; public ObservableCollection<TerminalSessionViewModel> Sessions{get;}=[]; [ObservableProperty] private CodexProfile? _selectedProfile; [ObservableProperty] private string _status="Create or import a profile to begin."; public MainWindowViewModel(string root,string defaultHome){_profiles=new(root,defaultHome);_activation=new(_profiles,root,defaultHome);_=ReloadAsync();} private async Task ReloadAsync(){var selected=SelectedProfile?.Id; Profiles.Clear(); foreach(var p in await _profiles.ListAsync()) Profiles.Add(p); SelectedProfile=Profiles.FirstOrDefault(x=>x.Id==selected)??Profiles.FirstOrDefault();}
[RelayCommand] private async Task Create(){SelectedProfile=await _profiles.CreateAsync("Profile "+(Profiles.Count+1));await ReloadAsync();Status="Isolated profile created.";}
[RelayCommand] private async Task Import(){SelectedProfile=await _profiles.ImportDefaultAsync("Imported "+(Profiles.Count+1));await ReloadAsync();Status="Current Codex home imported without modifying it.";}
[RelayCommand(CanExecute=nameof(HasSelection))] private void Launch(){var p=SelectedProfile!;var spec=_launch.Create(p,Environment.CurrentDirectory);Sessions.Add(_embedded.Launch(p.Name,spec));Status=$"Launched {p.Name} with isolated CODEX_HOME.";}
[RelayCommand(CanExecute=nameof(HasSelection))] private void External(){var p=SelectedProfile!;_external.Launch(_launch.Create(p,Environment.CurrentDirectory));Status=$"Opened {p.Name} externally.";}
[RelayCommand(CanExecute=nameof(HasSelection))] private async Task Activate(){var p=SelectedProfile!;await _activation.ActivateAsync(p);await ReloadAsync();Status=$"{p.Name} is now globally active. Existing default state was backed up.";}
private bool HasSelection()=>SelectedProfile is not null; partial void OnSelectedProfileChanged(CodexProfile? value){LaunchCommand.NotifyCanExecuteChanged();ExternalCommand.NotifyCanExecuteChanged();ActivateCommand.NotifyCanExecuteChanged();}
}
